// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "../WaveConstants.h"
#include "AlignSequence.h"
#include "WaveWait.h"
#include "SetArmPosition.h"
#include "SetIntake.h"
#include "SetTurretPosition.h"


AlignSequence::AlignSequence() {
	AddSequential(new SetArmPosition(c_armHighPosition));
	//trigger stuff for low bar. sensors are not on robot. cannot yet happen.

}
