// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoLowBar.h"
#include "AutoDriveDistance.h"
#include "DefenseCrossed.h"
#include "AutoDrivePower.h"
#include "../WaveConstants.h"
#include "FireSequence.h"
#include "SetArmPosition.h"
#include "SetTurretPosition.h"
#include "SetHoodPosition.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoLowBar::AutoLowBar() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.
              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
                      // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS


	AddSequential(new SetHoodPosition( Hood_Stow));

	AddSequential(new AutoDriveDistance(74, .5, 0));
	AddParallel(new SetArmPosition(c_armLowPosition));
	AddSequential(new DefenseCrossed(0.5));
	AddSequential(new DefenseCrossed(0.5)); //The Middle of The low bar defence is flat so we need to "cross" it twice
	AddSequential(new SetArmPosition(c_armTravelPosition));
	AddParallel(new AutoDrivePower(-.5, 0));
	//AddParallel(new ArmSensorsTripped()); // ok I made this command, whether or not it works is a different story.

	//Defense Is Crossed
	//AddSequential(new AutoDriveDistance(c_courtyard1, .5, 0));

	AddSequential(new SetTurretPosition(1, true));
	AddParallel(new SetHoodPosition(Hood_Medium));
	AddSequential(new FireSequence ());

	//Backing over the Defense
	AddSequential(new AutoDriveDistance(-c_courtyard1, -.5, 0));
	AddSequential(new DefenseCrossed (.5));
	AddSequential(new DefenseCrossed (.5));
	AddParallel(new AutoDrivePower (-.5,0));
	AddSequential(new AutoDrivePower (0,0));

}
