// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoPortcullis.h"
#include "ResetPitchAndRoll.h"
#include "SetHoodPosition.h"
#include "SetArmPosition.h"
#include "AutoDrivePower.h"
#include "DefenseCrossedSmart.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoPortcullis::AutoPortcullis() {

	//must set up backwards

	AddSequential(new ResetPitchAndRoll());
	AddSequential(new SetArmPosition(c_armLowPosition));
	AddParallel(new SetHoodPosition( Hood_Stow));
	AddParallel(new AutoDrivePower(.8, 0, true, false, false));
	AddSequential(new DefenseCrossedSmart(PitchStepIncrease, true, false));

 }
