// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoDrawbridge.h"

#include "DefenseCrossedSmart.h"
#include "AutoDrivePower.h"
#include "../WaveConstants.h"
#include "FireSequence.h"
#include "ResetPitchAndRoll.h"
#include "WaveWait.h"
#include "SetArmPosition.h"
#include "SetHeading.h"
#include "FirePrepSequence.h"



// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoDrawbridge::AutoDrawbridge() {

	AddSequential(new SetHeading(-90, false));

////This works on the Folske field with the open Portcullis
//	AddSequential(new ResetPitchAndRoll());
//	AddSequential(new SetArmPosition(c_armTravelPosition));
//	AddParallel(new FirePrepSequence(Hood_Medium, Turret_Straight, Long_Shot_Straight));
//	AddParallel(new DefenseCrossedSmart(PitchStepIncrease, false, false)); //not SURE if we need roll
//	AddSequential(new AutoDrivePower(.7, 0, true, false, false));
//	AddSequential(new SetHeading(-10, true));
//	AddSequential(new FireSequence());


}
