// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoRockWall.h"
#include "AutoDriveDistance.h"
#include "DefenseCrossedSmart.h"
#include "AutoDrivePower.h"
#include "../WaveConstants.h"
#include "FireSequence.h"
#include "SetTurretPosition.h"
#include "ResetPitchAndRoll.h"
#include "SetArmPosition.h"
#include "WaveWait.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoRockWall::AutoRockWall() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	AddSequential(new ResetPitchAndRoll());
	AddSequential(new SetArmPosition(c_armTravelPosition+5));
	//AddSequential(new FirePrepSequence(Hood_Medium, Turret_Straight, Long_Shot_Straight));
	AddParallel(new AutoDrivePower(.8, 0, true, false, false));
	AddSequential(new DefenseCrossedSmart(PitchStepIncrease, true, false)); //not SURE if we need roll
	AddSequential(new WaveWait(.25));
	AddParallel(new AutoDrivePower(0, 0,  false, false, false));
	AddSequential(new SetArmPosition(c_armIntakePosition));
	//need code for lining up
	//AddSequential(new FireSequence());

//	AddParallel(new AutoDrivePower(-.6, 0, true, false));
//	AddSequential(new DefenseCrossedSmart(PitchStepIncreaseBack, false, false));
//	AddSequential(new AutoDrivePower(0, 0, false, false));

	//AddSequential(new AutoDriveDistance(1, .5, 0, true));

	//AddSequential(new SetTurretPosition(1, true));
	//AddSequential(new FireSequence ());


}
