// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoChevalDeFrise.h"
#include "AutoDriveDistance.h"
#include "DefenseCrossed.h"
#include "AutoDrivePower.h"
#include "../WaveConstants.h"
#include "FireSequence.h"
#include "SetArmPosition.h"
#include "AutoCurve.h"
#include "SetTurretPosition.h"
#include "WaveWait.h"
#include "DefenseCrossedSmart.h"
#include "ResetPitchAndRoll.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoChevalDeFrise::AutoChevalDeFrise() {


	AddSequential(new ResetPitchAndRoll());
	AddSequential(new SetArmPosition(c_armTravelPosition));
	AddParallel(new AutoDrivePower(-.5, 0, true, false, false));
	AddSequential(new DefenseCrossedSmart(PitchStepIncreaseCDF, true, false)); //not SURE if we need roll
	AddSequential(new AutoDrivePower(.5, 0 , false, false, true));
	AddSequential(new AutoDrivePower(0, 0, false, false, false));
	AddSequential(new SetArmPosition(c_armLowPosition));
	//AddParallel(new AutoDrivePower(0, 0 , false, false));
	AddSequential (new WaveWait(.1));
	AddParallel(new AutoDrivePower(-.85, 0,  true, false, false));
	AddParallel(new DefenseCrossedSmart(PitchStepDecrease, true, false));
	AddSequential(new SetArmPosition(c_armTravelPosition));
	AddSequential(new WaveWait(.25));
	AddSequential(new SetArmPosition(c_armIntakePosition));
	AddParallel(new AutoDrivePower(0,0, false, false, false));
	AddSequential(new WaveWait(.25));
	AddSequential(new AutoDrivePower(.7, 180, false, false, false)); // NEEDS TO BE TESTED

//	AddSequential(new AutoDriveDistance(74, .5, 0));
//	AddSequential(new SetArmPosition(c_armLowPosition));
//	AddSequential(new DefenseCrossed(0.5));
//	AddParallel(new AutoDrivePower(.5, 0,  false, false));
//
//	//Defense Is Crossed
//
//	AddSequential(new AutoDriveDistance(1, .5, 0, true));
//
//	//AddSequential(new SetTurretPosition(1, true));
//	//AddSequential(new FireSequence ());
//
//	//Turn Around and Drive back over the Defense
//	AddSequential(new AutoCurve(180));
//	AddParallel(new SetArmPosition(c_armTravelPosition));
//	AddSequential(new AutoDriveDistance(1, .5, 180, true));
//	AddSequential(new SetArmPosition(c_armLowPosition));
//	AddSequential(new DefenseCrossed (.5));
//	AddParallel(new AutoDrivePower (.5,180,  false, false));
//	AddSequential(new AutoDrivePower (0,180,  false, false));

}
