// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DEFENSECROSSEDSmart_H
#define DEFENSECROSSEDSmart_H


#include "Commands/Subsystem.h"
#include "../Robot.h"
#include "time.h"

enum PitchStep {
		PitchStepIncrease,
		PitchStepDecrease,
		PitchStepFlat,
		PitchStepIncreaseBack
	};

/**
 *
 *
 * @author ExampleAuthor
 */
class DefenseCrossedSmart: public Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	DefenseCrossedSmart(PitchStep starStep, bool resetPitchRoll, bool checkRoll);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();


private:

	bool m_resetPitchRoll;
	bool m_checkRoll;

	int stepCounter;


};

#endif
