// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "FireSequence.h"
#include "SetShooterWheelSpeed.h"
#include "ShooterIntake.h"
#include "WaveWait.h"
#include "BallRelease.h"
#include "../Subsystems/ShooterWheelPID.h"
#include "SetTurretPosition.h"
#include "wpilib.h"


FireSequence::FireSequence() {
AddSequential(new ShooterIntake(true));
AddSequential(new WaveWait(2.0));
AddSequential(new ShooterIntake(false));

}
