// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "../WaveConstants.h"
#include "GrappleDeploy.h"
#include "WaveWait.h"
#include "SetArmPosition.h"
#include "SetIntake.h"
#include "SetTurretPosition.h"
#include "SetTurretCylinder.h"
#include "BallRelease.h"
#include "SetHoodPosition.h"
#include "SetGrappleState.h"


GrappleDeploy::GrappleDeploy() {
	AddSequential(new SetArmPosition(c_armIntakePosition)); //7 degrees
	AddSequential(new WaveWait(.25));
	AddSequential(new SetGrappleState(Grapple_Release));
	AddSequential(new WaveWait(.5));
	AddSequential(new SetArmPosition(c_armHighPosition)); //60 degrees
	AddSequential(new WaveWait(.25));
}
