// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#ifndef INTAKE_POSITION_SEQUENCE_H
#define INTAKE_POSITION_SEQUENCE_H
#include "../Subsystems/Intake.h"
#include "Commands/CommandGroup.h"
#include "BallRelease.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class IntakePositionSequence: public CommandGroup {
public:

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	IntakePositionSequence(TurretState state, ReleaseState ball);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

private:

};

#endif
