// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "../WaveConstants.h"
#include "SetHoodPositionSequence.h"
#include "WaveWait.h"
#include "SetHoodPosition.h"
#include "SetHoodLockPin.h"



SetHoodPositionSequence::SetHoodPositionSequence(HoodPosition position) {
AddSequential(new SetHoodLockPin(false));
AddSequential(new WaveWait(.5));
AddSequential(new SetHoodPosition(position));
AddSequential(new WaveWait(.5));
AddSequential(new SetHoodLockPin(true));
}
