// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "WaveWait.h"
#include <iostream>

WaveWait::WaveWait() {
	std::cout << "WaveWait construct - start & end" << std::endl;
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
WaveWait::WaveWait(double seconds){
    std::cout << "WaveWait(seconds) " << seconds << "  construct - start" << std::endl;
    SetTimeout(seconds);
	std::cout << "   WaveWait(seconds) construct - end" << std::endl;

}
// Called just before this Command runs the first time
void WaveWait::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void WaveWait::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool WaveWait::IsFinished() {
    if(IsTimedOut())
        {
            return true;
        }
	return false;
}
// Called once after isFinished returns true
void WaveWait::End() {
	std::cout << "Done waiting" << std::endl;
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void WaveWait::Interrupted() {
}
