// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<Joystick> operatorJoystick;
	std::shared_ptr<JoystickButton> operatorStart;
	std::shared_ptr<JoystickButton> operatorSelect;
	std::shared_ptr<JoystickButton> operatorRightBumper;
	std::shared_ptr<JoystickButton> operatorLeftBumper;
	std::shared_ptr<JoystickButton> operatorY;
	std::shared_ptr<JoystickButton> operatorX;
	std::shared_ptr<JoystickButton> operatorB;
	std::shared_ptr<JoystickButton> operatorA;
	std::shared_ptr<Joystick> driverJoystick;
	std::shared_ptr<JoystickButton> driverStart;
	std::shared_ptr<JoystickButton> driverSelect;
	std::shared_ptr<JoystickButton> driverRightBumper;
	std::shared_ptr<JoystickButton> driverLeftBumper;
	std::shared_ptr<JoystickButton> driverY;
	std::shared_ptr<JoystickButton> driverX;
	std::shared_ptr<JoystickButton> driverB;
	std::shared_ptr<JoystickButton> driverA;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<Joystick> getDriverJoystick();
	std::shared_ptr<Joystick> getOperatorJoystick();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
