// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
#include "AHRS.h"


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<Servo> climberClimbServo1;
	static std::shared_ptr<Servo> climberClimbServo2;
	static std::shared_ptr<CANTalon> intakeIntakeMotor;
	static std::shared_ptr<Encoder> drivePIDDriveEncoder;
	static std::shared_ptr<CANTalon> drivePIDLeftBack;
	static std::shared_ptr<CANTalon> drivePIDRightBack;
	static std::shared_ptr<CANTalon> drivePIDLeftFront;
	static std::shared_ptr<CANTalon> drivePIDRightFront;
	static std::shared_ptr<RobotDrive> drivePIDRobotDrive41;
	static std::shared_ptr<CANTalon> armPIDArmMotorRight;
	static std::shared_ptr<CANTalon> armPIDArmMotorLeft;
	static std::shared_ptr<Encoder> armPIDArmPosition;
	static std::shared_ptr<CANTalon> shooterWheelsShooter2;
	static std::shared_ptr<CANTalon> shooterWheelsShooter1;
	static std::shared_ptr<Encoder> shooterHeadPIDShooterPosition;
	static std::shared_ptr<CANTalon> shooterHeadPIDTrajectory;
	static std::shared_ptr<CANTalon> shooterHeadPIDStaging;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static std::shared_ptr<AHRS> m_gyro;


	static void init();
};
#endif
