// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::armPIDArmMotorRight;
std::shared_ptr<CANTalon> RobotMap::armPIDArmMotorLeft;
std::shared_ptr<Encoder> RobotMap::armPIDArmPosition;
std::shared_ptr<DigitalInput> RobotMap::armPIDLowBarProx1;
std::shared_ptr<DigitalInput> RobotMap::armPIDLowBarProx2;
std::shared_ptr<Compressor> RobotMap::compressorSubsystemWaveCompressor;
std::shared_ptr<Encoder> RobotMap::drivePIDDriveEncoderRight;
std::shared_ptr<Encoder> RobotMap::drivePIDDriveEncoderLeft;
std::shared_ptr<CANTalon> RobotMap::drivePIDLeftBack;
std::shared_ptr<CANTalon> RobotMap::drivePIDRightBack;
std::shared_ptr<CANTalon> RobotMap::drivePIDLeftFront;
std::shared_ptr<CANTalon> RobotMap::drivePIDRightFront;
std::shared_ptr<RobotDrive> RobotMap::drivePIDRobotDrive41;
std::shared_ptr<Solenoid> RobotMap::hoodShortCylinder;
std::shared_ptr<Solenoid> RobotMap::hoodLongCylinder;
std::shared_ptr<Solenoid> RobotMap::grappleClimbClimbRelease;
std::shared_ptr<Solenoid> RobotMap::grappleClimbGrappleRelease;
std::shared_ptr<CANTalon> RobotMap::intakeMainIntake;
std::shared_ptr<CANTalon> RobotMap::intakeSecondIntake;
std::shared_ptr<CANTalon> RobotMap::shooterTurretPIDTurretMotor;
std::shared_ptr<AnalogInput> RobotMap::shooterTurretPIDTurretAngle;
std::shared_ptr<DigitalInput> RobotMap::shooterTurretPIDTurretPosition1;
std::shared_ptr<DigitalInput> RobotMap::shooterTurretPIDTurretPosition2;
std::shared_ptr<DigitalInput> RobotMap::shooterTurretPIDTurretPosition3;
std::shared_ptr<CANTalon> RobotMap::shooterWheelPIDShooter1;
std::shared_ptr<Encoder> RobotMap::shooterWheelPIDNoUseEncoder;
std::shared_ptr<GearTooth> RobotMap::shooterWheelPIDSpeedCounter;
std::shared_ptr<CANTalon> RobotMap::shooterWheelPIDShooter2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

std::shared_ptr<AHRS> RobotMap::m_gyro;

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    armPIDArmMotorRight.reset(new CANTalon(5));
    lw->AddActuator("ArmPID", "ArmMotorRight", armPIDArmMotorRight);
    
    armPIDArmMotorLeft.reset(new CANTalon(4));
    lw->AddActuator("ArmPID", "ArmMotorLeft", armPIDArmMotorLeft);
    
    armPIDArmPosition.reset(new Encoder(4, 5, false, Encoder::k4X));
    lw->AddSensor("ArmPID", "ArmPosition", armPIDArmPosition);
    armPIDArmPosition->SetDistancePerPulse(1.0);
    armPIDArmPosition->SetPIDSourceType(PIDSourceType::kDisplacement);
    armPIDLowBarProx1.reset(new DigitalInput(9));
    lw->AddSensor("ArmPID", "LowBarProx1", armPIDLowBarProx1);
    
    armPIDLowBarProx2.reset(new DigitalInput(10));
    lw->AddSensor("ArmPID", "LowBarProx2", armPIDLowBarProx2);
    
    compressorSubsystemWaveCompressor.reset(new Compressor(0));
    
    
    drivePIDDriveEncoderRight.reset(new Encoder(0, 1, false, Encoder::k4X));
    lw->AddSensor("DrivePID", "DriveEncoderRight", drivePIDDriveEncoderRight);
    drivePIDDriveEncoderRight->SetDistancePerPulse(1.0);
    drivePIDDriveEncoderRight->SetPIDSourceType(PIDSourceType::kRate);
    drivePIDDriveEncoderLeft.reset(new Encoder(11, 12, false, Encoder::k4X));
    lw->AddSensor("DrivePID", "DriveEncoderLeft", drivePIDDriveEncoderLeft);
    drivePIDDriveEncoderLeft->SetDistancePerPulse(1.0);
    drivePIDDriveEncoderLeft->SetPIDSourceType(PIDSourceType::kRate);
    drivePIDLeftBack.reset(new CANTalon(1));
    lw->AddActuator("DrivePID", "LeftBack", drivePIDLeftBack);
    
    drivePIDRightBack.reset(new CANTalon(3));
    lw->AddActuator("DrivePID", "RightBack", drivePIDRightBack);
    
    drivePIDLeftFront.reset(new CANTalon(2));
    lw->AddActuator("DrivePID", "LeftFront", drivePIDLeftFront);
    
    drivePIDRightFront.reset(new CANTalon(11));
    lw->AddActuator("DrivePID", "RightFront", drivePIDRightFront);
    
    drivePIDRobotDrive41.reset(new RobotDrive(drivePIDLeftFront, drivePIDLeftBack,
              drivePIDRightFront, drivePIDRightBack));
    
    drivePIDRobotDrive41->SetSafetyEnabled(true);
        drivePIDRobotDrive41->SetExpiration(0.1);
        drivePIDRobotDrive41->SetSensitivity(0.5);
        drivePIDRobotDrive41->SetMaxOutput(1.0);

    hoodShortCylinder.reset(new Solenoid(0, 0));
    lw->AddActuator("Hood", "ShortCylinder", hoodShortCylinder);
    
    hoodLongCylinder.reset(new Solenoid(0, 1));
    lw->AddActuator("Hood", "LongCylinder", hoodLongCylinder);
    
    grappleClimbClimbRelease.reset(new Solenoid(0, 2));
    lw->AddActuator("GrappleClimb", "ClimbRelease", grappleClimbClimbRelease);
    
    grappleClimbGrappleRelease.reset(new Solenoid(0, 3));
    lw->AddActuator("GrappleClimb", "GrappleRelease", grappleClimbGrappleRelease);
    
    intakeMainIntake.reset(new CANTalon(6));
    lw->AddActuator("Intake", "MainIntake", intakeMainIntake);
    
    intakeSecondIntake.reset(new CANTalon(0));
    lw->AddActuator("Intake", "SecondIntake", intakeSecondIntake);
    
    shooterTurretPIDTurretMotor.reset(new CANTalon(9));
    lw->AddActuator("ShooterTurretPID", "TurretMotor", shooterTurretPIDTurretMotor);
    
    shooterTurretPIDTurretAngle.reset(new AnalogInput(0));
    lw->AddSensor("ShooterTurretPID", "TurretAngle", shooterTurretPIDTurretAngle);
    
    shooterTurretPIDTurretPosition1.reset(new DigitalInput(2));
    lw->AddSensor("ShooterTurretPID", "TurretPosition1", shooterTurretPIDTurretPosition1);
    
    shooterTurretPIDTurretPosition2.reset(new DigitalInput(3));
    lw->AddSensor("ShooterTurretPID", "TurretPosition2", shooterTurretPIDTurretPosition2);
    
    shooterTurretPIDTurretPosition3.reset(new DigitalInput(13));
    lw->AddSensor("ShooterTurretPID", "TurretPosition3", shooterTurretPIDTurretPosition3);
    
    shooterWheelPIDShooter1.reset(new CANTalon(7));
    lw->AddActuator("ShooterWheelPID", "Shooter1", shooterWheelPIDShooter1);
    
    shooterWheelPIDNoUseEncoder.reset(new Encoder(6, 8, false, Encoder::k4X));
    lw->AddSensor("ShooterWheelPID", "NoUseEncoder", shooterWheelPIDNoUseEncoder);
    shooterWheelPIDNoUseEncoder->SetDistancePerPulse(1.0);
    shooterWheelPIDNoUseEncoder->SetPIDSourceType(PIDSourceType::kRate);
    shooterWheelPIDSpeedCounter.reset(new GearTooth(7, false));
    lw->AddSensor("ShooterWheelPID", "SpeedCounter", shooterWheelPIDSpeedCounter);
    
    shooterWheelPIDShooter2.reset(new CANTalon(8));
    lw->AddActuator("ShooterWheelPID", "Shooter2", shooterWheelPIDShooter2);
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


    m_gyro.reset(new AHRS(SerialPort::kMXP));
}
