// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
#include "AHRS.h"


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<CANTalon> armPIDArmMotorRight;
	static std::shared_ptr<CANTalon> armPIDArmMotorLeft;
	static std::shared_ptr<DigitalInput> armPIDLowBarProx1;
	static std::shared_ptr<DigitalInput> armPIDLowBarProx2;
	static std::shared_ptr<Compressor> compressorSubsystemWaveCompressor;
	static std::shared_ptr<Encoder> drivePIDDriveEncoderRight;
	static std::shared_ptr<Encoder> drivePIDDriveEncoderLeft;
	static std::shared_ptr<CANTalon> drivePIDLeftBack;
	static std::shared_ptr<CANTalon> drivePIDRightBack;
	static std::shared_ptr<CANTalon> drivePIDLeftFront;
	static std::shared_ptr<CANTalon> drivePIDRightFront;
	static std::shared_ptr<RobotDrive> drivePIDRobotDrive41;
	static std::shared_ptr<Solenoid> hoodShortCylinder;
	static std::shared_ptr<Solenoid> hoodLongCylinder;
	static std::shared_ptr<Solenoid> grappleClimbClimbRelease;
	static std::shared_ptr<Solenoid> grappleClimbGrappleRelease;
	static std::shared_ptr<CANTalon> intakeMainIntake;
	static std::shared_ptr<CANTalon> intakeSecondIntake;
	static std::shared_ptr<CANTalon> shooterTurretPIDTurretMotor;
	static std::shared_ptr<AnalogInput> shooterTurretPIDTurretAngle;
	static std::shared_ptr<DigitalInput> shooterTurretPIDTurretPosition1;
	static std::shared_ptr<DigitalInput> shooterTurretPIDTurretPosition2;
	static std::shared_ptr<DigitalInput> shooterTurretPIDTurretPosition3;
	static std::shared_ptr<CANTalon> shooterWheelPIDShooter1;
	static std::shared_ptr<Encoder> shooterWheelPIDNoUseEncoder;
	static std::shared_ptr<GearTooth> shooterWheelPIDSpeedCounter;
	static std::shared_ptr<CANTalon> shooterWheelPIDShooter2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static std::shared_ptr<AnalogInput> armPIDArmAngle;
	static std::shared_ptr<Solenoid> intakeBallRelease;
	static std::shared_ptr<Solenoid> shooterTurretPIDTurretCylinder;
	static std::shared_ptr<Solenoid> hoodLockingCylinder;

	static std::shared_ptr<AHRS> m_gyro;


	static void init();
};
#endif
