// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

#define PracticeBot
//solenoids
int hoodcylindershort = 0;
int hoodcylinderlong = 1;
int turretcylinder = 5;
int shooterballrelease = 4;
int grapple = 3;
int climb = 2;

double wheelDiameter = 6.1; //inches

#ifdef PracticeBot
int CANTalon_drivePIDLeftBack = 1; //coast
int CANTalon_drivePIDLeftFront = 27; //coast
int CANTalon_drivePIDRightBack = 14; //coast
int CANTalon_drivePIDRightFront = 26; //coast
int CANTalon_primaryIntakeMotor = 7;
int CANTalon_secondaryIntakeMotor = 25;
int CANTalon_armMotorLeft = 4;
int CANTalon_armMotorRight = 9;
int CANTalon_shooterMotor1 = 16;
int CANTalon_shooterMotor2 = 17;
int CANTalon_turretMotor = 5;

double distancePerPulse = (wheelDiameter * 3.14159) / 128;
#endif


#ifdef CompBot
int CANTalon_drivePIDLeftBack = 1; //coast
int CANTalon_drivePIDLeftFront = 27; //coast
int CANTalon_drivePIDRightBack = 14; //coast
int CANTalon_drivePIDRightFront = 26; //coast
int CANTalon_primaryIntakeMotor = 2;
int CANTalon_secondaryIntakeMotor = 3;
int CANTalon_armMotorLeft = 4;
int CANTalon_armMotorRight = 5;
int CANTalon_shooterMotor1 = 6;
int CANTalon_shooterMotor2 = 7;
int CANTalon_turretMotor = 8;

double distancePerPulse = (wheelDiameter * 3.14159) / 256;
#endif


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::armPIDArmMotorRight;
std::shared_ptr<CANTalon> RobotMap::armPIDArmMotorLeft;
std::shared_ptr<DigitalInput> RobotMap::armPIDLowBarProx1;
std::shared_ptr<DigitalInput> RobotMap::armPIDLowBarProx2;
std::shared_ptr<Compressor> RobotMap::compressorSubsystemWaveCompressor;
std::shared_ptr<Encoder> RobotMap::drivePIDDriveEncoderRight;
std::shared_ptr<Encoder> RobotMap::drivePIDDriveEncoderLeft;
std::shared_ptr<CANTalon> RobotMap::drivePIDLeftBack;
std::shared_ptr<CANTalon> RobotMap::drivePIDRightBack;
std::shared_ptr<CANTalon> RobotMap::drivePIDLeftFront;
std::shared_ptr<CANTalon> RobotMap::drivePIDRightFront;
std::shared_ptr<RobotDrive> RobotMap::drivePIDRobotDrive41;
std::shared_ptr<Solenoid> RobotMap::hoodShortCylinder;
std::shared_ptr<Solenoid> RobotMap::hoodLongCylinder;
std::shared_ptr<Solenoid> RobotMap::grappleClimbClimbRelease;
std::shared_ptr<Solenoid> RobotMap::grappleClimbGrappleRelease;
std::shared_ptr<CANTalon> RobotMap::intakeMainIntake;
std::shared_ptr<CANTalon> RobotMap::intakeSecondIntake;
std::shared_ptr<CANTalon> RobotMap::shooterTurretPIDTurretMotor;
std::shared_ptr<AnalogInput> RobotMap::shooterTurretPIDTurretAngle;
std::shared_ptr<DigitalInput> RobotMap::shooterTurretPIDTurretPosition1;
std::shared_ptr<DigitalInput> RobotMap::shooterTurretPIDTurretPosition2;
std::shared_ptr<DigitalInput> RobotMap::shooterTurretPIDTurretPosition3;
std::shared_ptr<CANTalon> RobotMap::shooterWheelPIDShooter1;
std::shared_ptr<Encoder> RobotMap::shooterWheelPIDNoUseEncoder;
std::shared_ptr<GearTooth> RobotMap::shooterWheelPIDSpeedCounter;
std::shared_ptr<CANTalon> RobotMap::shooterWheelPIDShooter2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

std::shared_ptr<AnalogInput> RobotMap::armPIDArmAngle;
std::shared_ptr<Solenoid> RobotMap::intakeBallRelease;
std::shared_ptr<Solenoid> RobotMap::shooterTurretPIDTurretCylinder;

std::shared_ptr<AHRS> RobotMap::m_gyro;

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    armPIDArmMotorRight.reset(new CANTalon(CANTalon_armMotorRight));
    lw->AddActuator("ArmPID", "ArmMotorRight", armPIDArmMotorRight);
    
    armPIDArmAngle.reset(new AnalogInput(0));
    lw->AddActuator("ArmPID", "ArmAngle", armPIDArmAngle);

    armPIDLowBarProx1.reset(new DigitalInput(9));
    lw->AddSensor("ArmPID", "LowBarProx1", armPIDLowBarProx1);
    
    armPIDLowBarProx2.reset(new DigitalInput(10));
    lw->AddSensor("ArmPID", "LowBarProx2", armPIDLowBarProx2);
    
    compressorSubsystemWaveCompressor.reset(new Compressor(0));
    
    
    drivePIDDriveEncoderRight.reset(new Encoder(0, 1, false, Encoder::k4X));
    lw->AddSensor("DrivePID", "DriveEncoderRight", drivePIDDriveEncoderRight);
    drivePIDDriveEncoderRight->SetDistancePerPulse(distancePerPulse);
    drivePIDDriveEncoderRight->SetPIDSourceType(PIDSourceType::kRate);
    drivePIDDriveEncoderLeft.reset(new Encoder(11, 12, false, Encoder::k4X));
    lw->AddSensor("DrivePID", "DriveEncoderLeft", drivePIDDriveEncoderLeft);
    drivePIDDriveEncoderLeft->SetDistancePerPulse(distancePerPulse);
    drivePIDDriveEncoderLeft->SetPIDSourceType(PIDSourceType::kRate);
    drivePIDLeftBack.reset(new CANTalon(CANTalon_drivePIDLeftBack));
    lw->AddActuator("DrivePID", "LeftBack", drivePIDLeftBack);
    
    drivePIDRightBack.reset(new CANTalon(CANTalon_drivePIDRightBack));
    lw->AddActuator("DrivePID", "RightBack", drivePIDRightBack);
    
    drivePIDLeftFront.reset(new CANTalon(CANTalon_drivePIDLeftFront));
    lw->AddActuator("DrivePID", "LeftFront", drivePIDLeftFront);
    
    drivePIDRightFront.reset(new CANTalon(CANTalon_drivePIDRightFront));
    lw->AddActuator("DrivePID", "RightFront", drivePIDRightFront);
    
    drivePIDRobotDrive41.reset(new RobotDrive(drivePIDLeftFront, drivePIDLeftBack,
              drivePIDRightFront, drivePIDRightBack));
    
    drivePIDRobotDrive41->SetSafetyEnabled(true);
        drivePIDRobotDrive41->SetExpiration(0.1);
        drivePIDRobotDrive41->SetSensitivity(0.5);
        drivePIDRobotDrive41->SetMaxOutput(1.0);

    hoodShortCylinder.reset(new Solenoid(0, hoodcylindershort));
    lw->AddActuator("Hood", "ShortCylinder", hoodShortCylinder);
    
    hoodLongCylinder.reset(new Solenoid(0, hoodcylinderlong));
    lw->AddActuator("Hood", "LongCylinder", hoodLongCylinder);
    
    grappleClimbClimbRelease.reset(new Solenoid(0, climb));
    lw->AddActuator("GrappleClimb", "ClimbRelease", grappleClimbClimbRelease);
    
    grappleClimbGrappleRelease.reset(new Solenoid(0, grapple));
    lw->AddActuator("GrappleClimb", "GrappleRelease", grappleClimbGrappleRelease);
    
    intakeMainIntake.reset(new CANTalon(CANTalon_primaryIntakeMotor));
    lw->AddActuator("Intake", "MainIntake", intakeMainIntake);
    
    intakeSecondIntake.reset(new CANTalon(CANTalon_secondaryIntakeMotor));
    lw->AddActuator("Intake", "SecondIntake", intakeSecondIntake);
    
    shooterTurretPIDTurretMotor.reset(new CANTalon(CANTalon_turretMotor));
    lw->AddActuator("ShooterTurretPID", "TurretMotor", shooterTurretPIDTurretMotor);
    
    shooterTurretPIDTurretAngle.reset(new AnalogInput(0));
    lw->AddSensor("ShooterTurretPID", "TurretAngle", shooterTurretPIDTurretAngle);
    
    shooterTurretPIDTurretPosition1.reset(new DigitalInput(2));
    lw->AddSensor("ShooterTurretPID", "TurretPosition1", shooterTurretPIDTurretPosition1);
    
    shooterTurretPIDTurretPosition2.reset(new DigitalInput(3));
    lw->AddSensor("ShooterTurretPID", "TurretPosition2", shooterTurretPIDTurretPosition2);
    
    shooterTurretPIDTurretPosition3.reset(new DigitalInput(13));
    lw->AddSensor("ShooterTurretPID", "TurretPosition3", shooterTurretPIDTurretPosition3);
    
    shooterWheelPIDShooter1.reset(new CANTalon(CANTalon_shooterMotor1));
    lw->AddActuator("ShooterWheelPID", "Shooter1", shooterWheelPIDShooter1);
    
    shooterWheelPIDNoUseEncoder.reset(new Encoder(6, 8, false, Encoder::k4X));
    lw->AddSensor("ShooterWheelPID", "NoUseEncoder", shooterWheelPIDNoUseEncoder);
    shooterWheelPIDNoUseEncoder->SetDistancePerPulse(1.0);
    shooterWheelPIDNoUseEncoder->SetPIDSourceType(PIDSourceType::kRate);
    shooterWheelPIDSpeedCounter.reset(new GearTooth(7, false));
    lw->AddSensor("ShooterWheelPID", "SpeedCounter", shooterWheelPIDSpeedCounter);
    
    shooterWheelPIDShooter2.reset(new CANTalon(CANTalon_shooterMotor2));
    lw->AddActuator("ShooterWheelPID", "Shooter2", shooterWheelPIDShooter2);
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    armPIDArmMotorLeft.reset(new CANTalon(CANTalon_armMotorLeft));
    lw->AddActuator("ArmPID", "ArmMotorLeft", armPIDArmMotorLeft);

    intakeBallRelease.reset(new Solenoid(0, shooterballrelease));
    lw->AddActuator("Intake", "BallRelease", intakeBallRelease);

    shooterTurretPIDTurretCylinder.reset(new Solenoid(0, turretcylinder));
    lw->AddActuator("ShooterTurretPID", "TurretCylinder", shooterTurretPIDTurretCylinder);



    m_gyro.reset(new AHRS(SerialPort::kMXP));
}
